services:
  app:
    container_name: hotelaria_app
    restart: always
    build:
      context: .
      dockerfile: php/Dockerfile
      args:
        HTTP_PROXY: ${HTTP_PROXY}
        HTTPS_PROXY: ${HTTPS_PROXY}
        NO_PROXY: ${NO_PROXY}
    volumes:
      - ./src:/var/www
    command: >
      sh -c "
        chown -R www-data:www-data /var/www/storage /var/www/bootstrap/cache &&
        chmod -R 775 /var/www/storage /var/www/bootstrap/cache &&
        php-fpm
      "
    depends_on:
      - db

  nginx-init:
    image: alpine
    container_name: hotelaria_nginx_init
    restart: no
    volumes:
      - nginx-config:/etc/nginx/conf.d
      - ./nginx/default.conf:/default.conf:ro
    command: >
      sh -c "cp /default.conf /etc/nginx/conf.d/default.conf"

  web:
    image: nginx:alpine
    container_name: hotelaria_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - nginx-config:/etc/nginx/conf.d
      - ./src:/var/www
    depends_on:
      - nginx-init
      - app

  db:
    image: mysql:8
    container_name: hotelaria_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      TZ: ${APP_TIMEZONE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: hotelaria_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: ${PMA_PORT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - db

volumes:
  dbdata:
  nginx-config:
